export const templates: Record<string, unknown> = {
	siteInfo: {
		logo: '',
		labName: 'CREATE Lab',
		labFullName: 'Control, Robotics, and Autonomy Lab',
		institution: 'George Mason University',
		tagline: 'Dynamics, controls, and robotics at George Mason University',
		intro: '',
		heroImages: [],
		showAccessibility: true,
		alerts: [],
		highlights: [],
		contact: { department: '', address: [''], email: '' }
	},
	news: {
		title: '',
		author: '',
		date: '',
		body: '',
		linkType: 'none',
		href: '',
		slug: '',
		gallery: [],
		files: [],
		order: 0
	},
	projects: {
		title: '',
		summary: '',
		years: '',
		featured: false,
		tags: [],
		image: '',
		content: '',
		teamMembers: [],
		funding: [],
		links: [],
		gallery: [],
		files: [],
		relatedPublications: [],
		linkType: 'page',
		href: '',
		slug: '',
		order: 0
	},
	researchArticles: {
		slug: '',
		title: '',
		author: '',
		status: 'Active',
		image: '',
		content: '',
		gallery: [],
		files: [],
		relatedPublications: []
	},
	publications: {
		type: 'Journal Articles',
		title: '',
		authors: '',
		venue: '',
		date: '',
		doi: '',
		pdf: '',
		award: ''
	},
	team: {
		name: '',
		slug: '',
		role: 'member',
		group: 'Ph.D. Students',
		period: '',
		areaOfStudy: '',
		photo: '',
		note: '',
		bio: '',
		education: [{ degree: '', institution: '', years: '' }],
		email: '',
		socials: [{ kind: 'scholar', href: '', icon: '' }],
		order: 0
	},
	sponsors: { name: '', image: '', order: 0 },
	gallery: { title: '', image: '', order: 0 }
};
